#!/usr/bin/env php
<?php

declare(strict_types=1);

use Witals\Framework\Application;
use Witals\Framework\Console\ServeCommand;
use Witals\Framework\Contracts\RuntimeType;

define('WITALS_START', microtime(true));

// Register the Composer autoloader
require_once __DIR__ . '/vendor/autoload.php';

// Bootstrap the application
$app = require_once __DIR__ . '/bootstrap/app.php';

$argv = $_SERVER['argv'];

// Register core providers (this might already be done in registerConfiguredProviders)

/** @var \Witals\Framework\Console\Kernel $kernel */
$kernel = $app->make(\Witals\Framework\Console\Kernel::class);

$status = $kernel->handle($argv);

exit($status);
