<?php

declare(strict_types=1);

namespace PrestoWorld\Modules\ClassicTheme;

use PrestoWorld\Modules\ClassicTheme\Transformers\TransformerInterface;
use PrestoWorld\Modules\ClassicTheme\Transformers\FunctionTransformer;
use PrestoWorld\Modules\ClassicTheme\Transformers\ClassTransformer;

class TransformerRegistry
{
    private static array $functions = [];

    private static array $classes = [];

    private static array $instances = [];

    private static bool $discovered = false;

    public static function register(string $transformerClass): void
    {
        if (!is_subclass_of($transformerClass, TransformerInterface::class)) {
            return;
        }

        $reflector = new \ReflectionClass($transformerClass);

        if ($reflector->isAbstract() || $reflector->isInstantiable() === false) {
            return;
        }

        self::registerInstance($reflector->newInstance());
    }

    public static function registerInstance(TransformerInterface $instance): void
    {
        $name = $instance->handles();

        if ($instance instanceof FunctionTransformer) {
            self::$functions[$name] = $instance;
            self::$instances[$name] = $instance;
        } elseif ($instance instanceof ClassTransformer) {
            self::$classes[$name] = $instance;
        }
    }

    public static function registerFromDirectory(string $directory): void
    {
        if (self::$discovered || !is_dir($directory)) {
            return;
        }

        self::$discovered = true;

        $iterator = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($directory, \RecursiveDirectoryIterator::SKIP_DOTS),
        );

        foreach ($iterator as $file) {
            if ($file->getExtension() !== 'php') {
                continue;
            }

            $className = self::fileToClassName($file->getPathname(), $directory);

            if ($className !== null && is_subclass_of($className, TransformerInterface::class)) {
                $reflector = new \ReflectionClass($className);

                if (!$reflector->isAbstract()) {
                    self::registerInstance(new $className());
                }
            }
        }
    }

    public static function reset(): void
    {
        self::$functions = [];
        self::$classes = [];
        self::$instances = [];
        self::$discovered = false;
    }

    public static function call(string $function, array $args): mixed
    {
        $instance = self::$functions[$function] ?? null;

        if ($instance === null) {
            return null;
        }

        return $instance->handle(...$args);
    }

    public static function hasFunction(string $name): bool
    {
        return isset(self::$functions[$name]);
    }

    public static function hasClass(string $name): bool
    {
        return isset(self::$classes[$name]);
    }

    public static function defineClasses(): void
    {
        foreach (self::$classes as $name => $instance) {
            if (class_exists($name, false)) {
                continue;
            }

            $instance->define();
        }
    }

    public static function getRegisteredFunctions(): array
    {
        return array_keys(self::$functions);
    }

    public static function getRegisteredClasses(): array
    {
        return array_keys(self::$classes);
    }

    public static function generateStubs(): string
    {
        $stubs = "<?php\n\n";
        $stubs .= "declare(strict_types=1);\n\n";
        $stubs .= "// This file is auto-generated by 'php witals presto:generate-stubs'.\n";
        $stubs .= "// Do not edit manually. Add/modify transformers in Transformers/ directory.\n\n";

        $functionNames = self::getRegisteredFunctions();
        sort($functionNames);

        foreach ($functionNames as $name) {
            $stubs .= self::generateFunctionStub($name);
        }

        $classNames = self::getRegisteredClasses();
        sort($classNames);

        foreach ($classNames as $name) {
            $stubs .= self::generateClassStub($name);
        }

        return $stubs;
    }

    private static function generateFunctionStub(string $name): string
    {
        $safeName = var_export($name, true);

        return <<<PHP
if (!function_exists('{$name}')) {
    function {$name}(mixed ...\$args): mixed
    {
        return \\PrestoWorld\\Modules\\ClassicTheme\\TransformerRegistry::call({$safeName}, \$args);
    }
}

PHP;
    }

    private static function generateClassStub(string $name): string
    {
        return <<<PHP
if (!class_exists('{$name}')) {
    (static function (): void {
        \\PrestoWorld\\Modules\\ClassicTheme\\TransformerRegistry::defineClasses();
    })();
}

PHP;
    }

    private static function fileToClassName(string $filePath, string $baseDir): ?string
    {
        $relativePath = str_replace($baseDir, '', $filePath);
        $relativePath = ltrim($relativePath, '/');
        $relativePath = str_replace('.php', '', $relativePath);

        $parts = explode('/', $relativePath);
        $namespaceParts = ['PrestoWorld', 'Modules', 'ClassicTheme', 'Transformers'];

        foreach ($parts as $part) {
            $namespaceParts[] = self::phpize($part);
        }

        $className = implode('\\', $namespaceParts);

        if (!class_exists($className)) {
            return null;
        }

        return $className;
    }

    private static function phpize(string $name): string
    {
        $name = str_replace(['-', '_'], ' ', $name);
        $name = ucwords($name);
        return str_replace(' ', '', $name);
    }
}
