<?php

declare(strict_types=1);

// This file is auto-generated by 'php witals presto:generate-stubs'.
// Do not edit manually. Add/modify transformers in Transformers/ directory.

if (!function_exists('_e')) {
    function _e(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('_e', $args);
    }
}
if (!function_exists('_ex')) {
    function _ex(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('_ex', $args);
    }
}
if (!function_exists('_n')) {
    function _n(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('_n', $args);
    }
}
if (!function_exists('_x')) {
    function _x(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('_x', $args);
    }
}
if (!function_exists('add_action')) {
    function add_action(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('add_action', $args);
    }
}
if (!function_exists('add_editor_style')) {
    function add_editor_style(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('add_editor_style', $args);
    }
}
if (!function_exists('add_filter')) {
    function add_filter(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('add_filter', $args);
    }
}
if (!function_exists('add_image_size')) {
    function add_image_size(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('add_image_size', $args);
    }
}
if (!function_exists('add_theme_support')) {
    function add_theme_support(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('add_theme_support', $args);
    }
}
if (!function_exists('admin_url')) {
    function admin_url(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('admin_url', $args);
    }
}
if (!function_exists('apply_filters')) {
    function apply_filters(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('apply_filters', $args);
    }
}
if (!function_exists('bloginfo')) {
    function bloginfo(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('bloginfo', $args);
    }
}
if (!function_exists('body_class')) {
    function body_class(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('body_class', $args);
    }
}
if (!function_exists('comment_form')) {
    function comment_form(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('comment_form', $args);
    }
}
if (!function_exists('comments_open')) {
    function comments_open(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('comments_open', $args);
    }
}
if (!function_exists('date_i18n')) {
    function date_i18n(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('date_i18n', $args);
    }
}
if (!function_exists('do_action')) {
    function do_action(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('do_action', $args);
    }
}
if (!function_exists('dynamic_sidebar')) {
    function dynamic_sidebar(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('dynamic_sidebar', $args);
    }
}
if (!function_exists('esc_attr')) {
    function esc_attr(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('esc_attr', $args);
    }
}
if (!function_exists('esc_attr_e')) {
    function esc_attr_e(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('esc_attr_e', $args);
    }
}
if (!function_exists('esc_attr_x')) {
    function esc_attr_x(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('esc_attr_x', $args);
    }
}
if (!function_exists('esc_html')) {
    function esc_html(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('esc_html', $args);
    }
}
if (!function_exists('esc_html_e')) {
    function esc_html_e(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('esc_html_e', $args);
    }
}
if (!function_exists('esc_url')) {
    function esc_url(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('esc_url', $args);
    }
}
if (!function_exists('get_avatar')) {
    function get_avatar(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('get_avatar', $args);
    }
}
if (!function_exists('get_bloginfo')) {
    function get_bloginfo(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('get_bloginfo', $args);
    }
}
if (!function_exists('get_custom_logo')) {
    function get_custom_logo(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('get_custom_logo', $args);
    }
}
if (!function_exists('get_footer')) {
    function get_footer(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('get_footer', $args);
    }
}
if (!function_exists('get_header')) {
    function get_header(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('get_header', $args);
    }
}
if (!function_exists('get_home_url')) {
    function get_home_url(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('get_home_url', $args);
    }
}
if (!function_exists('get_option')) {
    function get_option(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('get_option', $args);
    }
}
if (!function_exists('get_permalink')) {
    function get_permalink(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('get_permalink', $args);
    }
}
if (!function_exists('get_post_type')) {
    function get_post_type(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('get_post_type', $args);
    }
}
if (!function_exists('get_queried_object_id')) {
    function get_queried_object_id(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('get_queried_object_id', $args);
    }
}
if (!function_exists('get_query_var')) {
    function get_query_var(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('get_query_var', $args);
    }
}
if (!function_exists('get_search_form')) {
    function get_search_form(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('get_search_form', $args);
    }
}
if (!function_exists('get_search_query')) {
    function get_search_query(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('get_search_query', $args);
    }
}
if (!function_exists('get_sidebar')) {
    function get_sidebar(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('get_sidebar', $args);
    }
}
if (!function_exists('get_stylesheet_directory')) {
    function get_stylesheet_directory(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('get_stylesheet_directory', $args);
    }
}
if (!function_exists('get_stylesheet_uri')) {
    function get_stylesheet_uri(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('get_stylesheet_uri', $args);
    }
}
if (!function_exists('get_template_directory')) {
    function get_template_directory(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('get_template_directory', $args);
    }
}
if (!function_exists('get_template_directory_uri')) {
    function get_template_directory_uri(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('get_template_directory_uri', $args);
    }
}
if (!function_exists('get_template_part')) {
    function get_template_part(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('get_template_part', $args);
    }
}
if (!function_exists('get_the_ID')) {
    function get_the_ID(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('get_the_ID', $args);
    }
}
if (!function_exists('get_the_archive_description')) {
    function get_the_archive_description(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('get_the_archive_description', $args);
    }
}
if (!function_exists('get_the_archive_title')) {
    function get_the_archive_title(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('get_the_archive_title', $args);
    }
}
if (!function_exists('get_the_author_meta')) {
    function get_the_author_meta(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('get_the_author_meta', $args);
    }
}
if (!function_exists('get_the_post_thumbnail')) {
    function get_the_post_thumbnail(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('get_the_post_thumbnail', $args);
    }
}
if (!function_exists('get_the_posts_pagination')) {
    function get_the_posts_pagination(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('get_the_posts_pagination', $args);
    }
}
if (!function_exists('get_the_title')) {
    function get_the_title(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('get_the_title', $args);
    }
}
if (!function_exists('get_theme_file_path')) {
    function get_theme_file_path(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('get_theme_file_path', $args);
    }
}
if (!function_exists('get_theme_file_uri')) {
    function get_theme_file_uri(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('get_theme_file_uri', $args);
    }
}
if (!function_exists('get_theme_mod')) {
    function get_theme_mod(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('get_theme_mod', $args);
    }
}
if (!function_exists('get_theme_support')) {
    function get_theme_support(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('get_theme_support', $args);
    }
}
if (!function_exists('has_custom_logo')) {
    function has_custom_logo(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('has_custom_logo', $args);
    }
}
if (!function_exists('has_nav_menu')) {
    function has_nav_menu(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('has_nav_menu', $args);
    }
}
if (!function_exists('has_post_thumbnail')) {
    function has_post_thumbnail(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('has_post_thumbnail', $args);
    }
}
if (!function_exists('have_posts')) {
    function have_posts(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('have_posts', $args);
    }
}
if (!function_exists('home_url')) {
    function home_url(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('home_url', $args);
    }
}
if (!function_exists('is_404')) {
    function is_404(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('is_404', $args);
    }
}
if (!function_exists('is_active_sidebar')) {
    function is_active_sidebar(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('is_active_sidebar', $args);
    }
}
if (!function_exists('is_admin')) {
    function is_admin(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('is_admin', $args);
    }
}
if (!function_exists('is_archive')) {
    function is_archive(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('is_archive', $args);
    }
}
if (!function_exists('is_customize_preview')) {
    function is_customize_preview(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('is_customize_preview', $args);
    }
}
if (!function_exists('is_front_page')) {
    function is_front_page(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('is_front_page', $args);
    }
}
if (!function_exists('is_home')) {
    function is_home(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('is_home', $args);
    }
}
if (!function_exists('is_page')) {
    function is_page(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('is_page', $args);
    }
}
if (!function_exists('is_paged')) {
    function is_paged(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('is_paged', $args);
    }
}
if (!function_exists('is_search')) {
    function is_search(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('is_search', $args);
    }
}
if (!function_exists('is_single')) {
    function is_single(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('is_single', $args);
    }
}
if (!function_exists('is_singular')) {
    function is_singular(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('is_singular', $args);
    }
}
if (!function_exists('language_attributes')) {
    function language_attributes(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('language_attributes', $args);
    }
}
if (!function_exists('number_format_i18n')) {
    function number_format_i18n(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('number_format_i18n', $args);
    }
}
if (!function_exists('register_nav_menus')) {
    function register_nav_menus(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('register_nav_menus', $args);
    }
}
if (!function_exists('register_sidebar')) {
    function register_sidebar(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('register_sidebar', $args);
    }
}
if (!function_exists('sanitize_text_field')) {
    function sanitize_text_field(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('sanitize_text_field', $args);
    }
}
if (!function_exists('set_post_thumbnail_size')) {
    function set_post_thumbnail_size(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('set_post_thumbnail_size', $args);
    }
}
if (!function_exists('site_url')) {
    function site_url(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('site_url', $args);
    }
}
if (!function_exists('the_ID')) {
    function the_ID(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('the_ID', $args);
    }
}
if (!function_exists('the_content')) {
    function the_content(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('the_content', $args);
    }
}
if (!function_exists('the_custom_logo')) {
    function the_custom_logo(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('the_custom_logo', $args);
    }
}
if (!function_exists('the_permalink')) {
    function the_permalink(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('the_permalink', $args);
    }
}
if (!function_exists('the_post')) {
    function the_post(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('the_post', $args);
    }
}
if (!function_exists('the_post_thumbnail')) {
    function the_post_thumbnail(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('the_post_thumbnail', $args);
    }
}
if (!function_exists('the_posts_pagination')) {
    function the_posts_pagination(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('the_posts_pagination', $args);
    }
}
if (!function_exists('the_privacy_policy_link')) {
    function the_privacy_policy_link(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('the_privacy_policy_link', $args);
    }
}
if (!function_exists('the_title')) {
    function the_title(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('the_title', $args);
    }
}
if (!function_exists('wp_add_inline_script')) {
    function wp_add_inline_script(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('wp_add_inline_script', $args);
    }
}
if (!function_exists('wp_add_inline_style')) {
    function wp_add_inline_style(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('wp_add_inline_style', $args);
    }
}
if (!function_exists('wp_body_open')) {
    function wp_body_open(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('wp_body_open', $args);
    }
}
if (!function_exists('wp_date')) {
    function wp_date(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('wp_date', $args);
    }
}
if (!function_exists('wp_doing_ajax')) {
    function wp_doing_ajax(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('wp_doing_ajax', $args);
    }
}
if (!function_exists('wp_enqueue_script')) {
    function wp_enqueue_script(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('wp_enqueue_script', $args);
    }
}
if (!function_exists('wp_enqueue_style')) {
    function wp_enqueue_style(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('wp_enqueue_style', $args);
    }
}
if (!function_exists('wp_footer')) {
    function wp_footer(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('wp_footer', $args);
    }
}
if (!function_exists('wp_get_attachment_image_src')) {
    function wp_get_attachment_image_src(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('wp_get_attachment_image_src', $args);
    }
}
if (!function_exists('wp_get_theme')) {
    function wp_get_theme(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('wp_get_theme', $args);
    }
}
if (!function_exists('wp_get_theme_file_path')) {
    function wp_get_theme_file_path(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('wp_get_theme_file_path', $args);
    }
}
if (!function_exists('wp_head')) {
    function wp_head(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('wp_head', $args);
    }
}
if (!function_exists('wp_json_encode')) {
    function wp_json_encode(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('wp_json_encode', $args);
    }
}
if (!function_exists('wp_kses')) {
    function wp_kses(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('wp_kses', $args);
    }
}
if (!function_exists('wp_kses_post')) {
    function wp_kses_post(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('wp_kses_post', $args);
    }
}
if (!function_exists('wp_link_pages')) {
    function wp_link_pages(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('wp_link_pages', $args);
    }
}
if (!function_exists('wp_list_comments')) {
    function wp_list_comments(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('wp_list_comments', $args);
    }
}
if (!function_exists('wp_list_pages')) {
    function wp_list_pages(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('wp_list_pages', $args);
    }
}
if (!function_exists('wp_localize_script')) {
    function wp_localize_script(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('wp_localize_script', $args);
    }
}
if (!function_exists('wp_nav_menu')) {
    function wp_nav_menu(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('wp_nav_menu', $args);
    }
}
if (!function_exists('wp_parse_args')) {
    function wp_parse_args(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('wp_parse_args', $args);
    }
}
if (!function_exists('wp_strip_all_tags')) {
    function wp_strip_all_tags(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('wp_strip_all_tags', $args);
    }
}
if (!function_exists('wp_style_add_data')) {
    function wp_style_add_data(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('wp_style_add_data', $args);
    }
}
if (!function_exists('wpautop')) {
    function wpautop(mixed ...$args): mixed
    {
        return \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::call('wpautop', $args);
    }
}
if (!class_exists('WP_Customize_Control')) {
    (static function (): void {
        \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::defineClasses();
    })();
}
if (!class_exists('WP_Customize_Manager')) {
    (static function (): void {
        \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::defineClasses();
    })();
}
if (!class_exists('Walker')) {
    (static function (): void {
        \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::defineClasses();
    })();
}
if (!class_exists('Walker_Comment')) {
    (static function (): void {
        \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::defineClasses();
    })();
}
if (!class_exists('Walker_Nav_Menu')) {
    (static function (): void {
        \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::defineClasses();
    })();
}
if (!class_exists('Walker_Page')) {
    (static function (): void {
        \PrestoWorld\Modules\ClassicTheme\TransformerRegistry::defineClasses();
    })();
}
